name: Deploy to Vercel and clean up old deployments

on:
  push:
    branches:
      - main  # Ganti dengan branch yang kamu gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Vercel
      run: |
        npm install -g vercel
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

    - name: Get Vercel deployments
      run: |
        # Mendapatkan list deployment dan memproses output dengan jq
        deployments=$(vercel ls --token ${{ secrets.VERCEL_TOKEN }} | grep -oP '(?<=https:\/\/data-center-)[^ ]*')  # Ambil UID dari URL
        echo "Deployments: $deployments"

    - name: Remove old deployments
      run: |
        # Periksa jumlah deployment yang ada
        num_deployments=$(echo "$deployments" | wc -l)
        echo "Number of deployments: $num_deployments"

        if [ "$num_deployments" -gt 1 ]; then
          # Ambil deployment kedua dan lebih lama (jika ada)
          old_deployment=$(echo "$deployments" | sed -n '2p')  # Ambil deployment kedua dari list

          if [ ! -z "$old_deployment" ]; then
            echo "Removing old deployment $old_deployment"
            vercel rm $old_deployment --token ${{ secrets.VERCEL_TOKEN }} --yes
          else
            echo "No old deployment found to remove"
          fi
        else
          echo "Only one deployment found, no old deployment to remove"
        fi
